### ISSUE TITLE
[Feature] A flat directory structure for output

### ISSUE THREAD

**Issue by NickLarsenNZ** [nathforge/kubectl-save#3]
Thanks for making this plugin.

It would be nice to have the output files all in a single directory. 

For example, instead of: `grafana/apps_v1--Deployment/default--grafana.yaml` it could be `grafana/apps_v1--Deployment--default--grafana.yaml`

**Comment by nathforge** [comment]
Thanks Nick - you should be able to use the `-t` flag for this, it defaults to `{{.apiVersion}}--{{.kind}}/{{.namespace}}--{{.name}}.yaml`

So e.g for your example something like `kubectl split-yaml -t "{{.apiVersion}}--{{.kind}}--{{.namespace}}--{{.name}}.yaml"`

**Comment by NickLarsenNZ** [comment]
Perfect, I somehow missed that option.
